<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Grpc.Core.Api" Version="2.70.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentIt.Bookings.Contracts\RentIt.Bookings.Contracts.csproj" />
    <ProjectReference Include="..\RentIt.Bookings.Core\RentIt.Bookings.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RentIt.MessageBroker.Contracts">
      <HintPath>..\..\RentIt.MessageBroker\RentIt.MessageBroker.Contracts\bin\Debug\net8.0\RentIt.MessageBroker.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="RentIt.Protos">
      <HintPath>..\..\RentIt.Protos\RentIt.Protos\bin\Debug\net8.0\RentIt.Protos.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
