version: '3.8'
services:
  users_service:
    build:
      context: ./RentIt.Users
      dockerfile: Dockerfile       
    container_name: rentit_users_service
    environment:
      - ConnectionStrings__UsersDatabaseConnection=Server=users_db;Port=5432;Database=users_db;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - users_db
      - redis

  users_db:
    image: postgres:14
    container_name: rentit_users_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"  
    volumes:
      - ./postgres_data_users:/var/lib/postgresql/data

  booking_db:
    image: postgres:14
    container_name: rentit_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_db
    ports:
      - "5434:5432"  
    volumes:
      - ./postgres_data_booking:/var/lib/postgresql/data

  housing_mongo:
    image: mongo:6
    container_name: rentit_properties_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: properties_db
    ports:
      - "27018:27017"  
    volumes:
      - ./mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: rentit_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data